title: <p align="center"> Sanvid Indalkar </p>
description:   
  <p align="center"> |
  <a style="color:White;" href="https://www.linkedin.com/in/hrithikjoshi/">LinkedIn</a> |
  <a style="color:White;" href="https://github.com/SanvidIndalkar">GitHub</a> |
  
  <br>
  <br>

  <br>
  I have hands on experience on Python,C++, React.js,HTML and CSS.
  <br>
  </p>

theme: jekyll-theme-cayman
