title: <p align="center"> Hrithik Joshi </p>
description:   
  <p align="center"> |
  <a href="https://www.linkedin.com/in/hrithikjoshi/">LinkedIn</a> |
  <a href="https://github.com/hrithikjoshi">GitHub</a>
  
  <br>   
  Working as a Data Science Trainee at TuringMinds.ai
  I have hands-on experience in Python (Numpy, Pandas, Matplotlib, Seaborn), 
  MySQL, SQLite, Tableau, R Programming Language (ggplot), Statistics and Probability 
  <br>
  </p>

theme: jekyll-theme-cayman
